sonar.projectKey=eeshanoor_rest-api-automation
sonar.projectName=REST API Automation
sonar.projectVersion=1.0
sonar.sources=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports
sonar.qualitygate.wait=true